# Generated by Django 5.2.6 on 2025-10-09 13:44

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('is_system', models.BooleanField(default=False)),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tags',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=128)),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('UPLOADING', 'Uploading'),
                            ('PENDING', 'Pending'),
                            ('PROCESSING', 'Processing'),
                            ('READY', 'Ready'),
                            ('FAILED', 'Failed'),
                            ('ARCHIVED', 'Archived'),
                        ],
                        default='UPLOADING',
                        max_length=16,
                    ),
                ),
                (
                    'duration_seconds',
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ('bitrate_kbps', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'loudness_lufs',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    'peak_dbfs',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('processed_storage_key', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('is_explicit', models.BooleanField(default=False)),
                (
                    'is_duplicate_of',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='duplicates',
                        to='medias.track',
                    ),
                ),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tracks',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='TrackAsset',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'asset_type',
                    models.CharField(
                        choices=[
                            ('RAW_ORIGINAL', 'Raw Original'),
                            ('NORMALIZED_MP3', 'Normalized Mp3'),
                            ('WAVEFORM_JSON', 'Waveform Json'),
                            ('COVER_ART', 'Cover Art'),
                            ('ALT_ENCODING', 'Alt Encoding'),
                        ],
                        max_length=32,
                    ),
                ),
                ('storage_key', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                (
                    'track',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assets',
                        to='medias.track',
                    ),
                ),
            ],
            options={
                'db_table': 'track_assets',
            },
        ),
        migrations.CreateModel(
            name='TrackTag',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('relevance', models.FloatField(default=1.0)),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='medias.tag'
                    ),
                ),
                (
                    'track',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='medias.track'
                    ),
                ),
            ],
            options={
                'db_table': 'track_tags',
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('DIRECT', 'Direct'),
                            ('ADMIN_PANEL', 'Admin Panel'),
                            ('API', 'Api'),
                        ],
                        default='DIRECT',
                        max_length=16,
                    ),
                ),
                ('storage_incoming_key', models.CharField(blank=True, max_length=512)),
                ('finalized', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='upload_sessions',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'upload_sessions',
            },
        ),
        migrations.CreateModel(
            name='TranscodeJob',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('QUEUED', 'Queued'),
                            ('RUNNING', 'Running'),
                            ('SUCCESS', 'Success'),
                            ('FAILED', 'Failed'),
                            ('CANCELED', 'Canceled'),
                        ],
                        default='QUEUED',
                        max_length=12,
                    ),
                ),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=64)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('input_storage_key', models.CharField(blank=True, max_length=512)),
                ('output_storage_key', models.CharField(blank=True, max_length=512)),
                (
                    'loudness_lufs',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    'peak_dbfs',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    'target_bitrate_kbps',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transcode_jobs',
                        to='studio.studio',
                    ),
                ),
                (
                    'track',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transcode_jobs',
                        to='medias.track',
                    ),
                ),
                (
                    'upload_session',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='transcode_jobs',
                        to='medias.uploadsession',
                    ),
                ),
            ],
            options={
                'db_table': 'transcode_jobs',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='upload_session',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tracks',
                to='medias.uploadsession',
            ),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(
                fields=['studio', 'name'], name='tags_studio__a16630_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('studio', 'name')},
        ),
        migrations.AddIndex(
            model_name='trackasset',
            index=models.Index(
                fields=['track', 'asset_type'], name='track_asset_track_i_48792d_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='trackasset',
            unique_together={('track', 'asset_type', 'storage_key')},
        ),
        migrations.AlterUniqueTogether(
            name='tracktag',
            unique_together={('track', 'tag')},
        ),
        migrations.AddIndex(
            model_name='transcodejob',
            index=models.Index(
                fields=['studio', 'status'], name='transcode_j_studio__bb5a96_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='transcodejob',
            index=models.Index(
                fields=['track', 'status'], name='transcode_j_track_i_382618_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(
                fields=['studio', 'state'], name='tracks_studio__e08ac3_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(
                fields=['studio', 'is_active', 'state'],
                name='tracks_studio__8af275_idx',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('studio', 'content_hash')},
        ),
    ]
