# Generated by Django 5.2.7 on 2025-10-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='bytes_received',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='temp_rel_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='upload_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
