# Generated by Django 5.2.7 on 2025-10-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_uploadsession_bytes_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='processed_storage_key',
            new_name='processed_rel_path',
        ),
        migrations.AddField(
            model_name='track',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
