# Generated by Django 5.2.6 on 2025-10-09 13:40

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_bitrate_kbps', models.PositiveIntegerField(default=128)),
                ('auto_normalize', models.BooleanField(default=True)),
                (
                    'loudness_target_lufs',
                    models.DecimalField(decimal_places=2, default=-14.0, max_digits=5),
                ),
            ],
            options={
                'db_table': 'studios',
                'indexes': [
                    models.Index(fields=['slug'], name='studios_slug_2b7a0a_idx')
                ],
            },
        ),
        migrations.CreateModel(
            name='ScheduledShow',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='shows',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'scheduled_shows',
            },
        ),
        migrations.CreateModel(
            name='RotationRule',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('rule_json', models.JSONField(blank=True, default=dict)),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rotation_rules',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'rotation_rules',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rotation', models.BooleanField(default=False)),
                ('avoid_recent_minutes', models.PositiveIntegerField(default=30)),
                ('max_daily_spins', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='playlists',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='AUTO', max_length=16)),
                ('sequence', models.BigIntegerField()),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='play_events',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'play_events',
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'state',
                    models.CharField(
                        choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')],
                        default='ACTIVE',
                        max_length=8,
                    ),
                ),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source_ip_hash', models.CharField(blank=True, max_length=64)),
                ('mountpoint', models.CharField(blank=True, max_length=128)),
                ('metadata_name', models.CharField(blank=True, max_length=255)),
                (
                    'metadata_bitrate',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'started_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='live_started_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='live_sessions',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'live_sessions',
            },
        ),
        migrations.CreateModel(
            name='ListenerStatBucket',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'interval',
                    models.CharField(
                        choices=[
                            ('MINUTE', 'Minute'),
                            ('FIVE_MIN', 'Five Minutes'),
                            ('HOUR', 'Hour'),
                        ],
                        default='MINUTE',
                        max_length=16,
                    ),
                ),
                ('bucket_start', models.DateTimeField(db_index=True)),
                ('active_peak', models.PositiveIntegerField()),
                ('listener_minutes', models.PositiveIntegerField()),
                ('countries_json', models.JSONField(default=dict)),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='listener_buckets',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'listener_stat_buckets',
            },
        ),
        migrations.CreateModel(
            name='ListenerSession',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                (
                    'ended_at',
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('client_type', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=128)),
                (
                    'lat',
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    'lon',
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ('total_bytes', models.BigIntegerField(default=0)),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='listener_sessions',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'listener_sessions',
            },
        ),
        migrations.CreateModel(
            name='StudioMembership',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('OWNER', 'Owner'),
                            ('ADMIN', 'Admin'),
                            ('EDITOR', 'Editor'),
                            ('DJ', 'Dj'),
                            ('ANALYST', 'Analyst'),
                            ('VIEWER', 'Viewer'),
                        ],
                        default='VIEWER',
                        max_length=16,
                    ),
                ),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='memberships',
                        to='studio.studio',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='studio_memberships',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'studio_memberships',
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('weight', models.FloatField(default=1.0)),
                ('start_offset_ms', models.PositiveIntegerField(default=0)),
                (
                    'playlist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='studio.playlist',
                    ),
                ),
            ],
            options={
                'db_table': 'playlist_items',
                'ordering': ['position'],
                'indexes': [
                    models.Index(
                        fields=['playlist', 'position'],
                        name='playlist_it_playlis_55432e_idx',
                    )
                ],
                'unique_together': {('playlist', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ShowSlot',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'mode',
                    models.CharField(
                        choices=[
                            ('PLAYLIST', 'Playlist'),
                            ('LIVE_REQUIRED', 'Live Required'),
                            ('ROTATION', 'Rotation'),
                            ('SILENCE', 'Silence'),
                        ],
                        default='PLAYLIST',
                        max_length=16,
                    ),
                ),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255)),
                (
                    'playlist',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='show_slots',
                        to='studio.playlist',
                    ),
                ),
                (
                    'show',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='slots',
                        to='studio.scheduledshow',
                    ),
                ),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='show_slots',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'show_slots',
                'indexes': [
                    models.Index(
                        fields=['studio', 'starts_at'],
                        name='show_slots_studio__34b9bf_idx',
                    ),
                    models.Index(
                        fields=['show', 'starts_at'],
                        name='show_slots_show_id_fcea5d_idx',
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledshow',
            index=models.Index(
                fields=['studio', 'title'], name='scheduled_s_studio__5f8774_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='rotationrule',
            unique_together={('studio', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('studio', 'name')},
        ),
        migrations.AddIndex(
            model_name='playevent',
            index=models.Index(
                fields=['studio', 'started_at'], name='play_events_studio__0bbd88_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='playevent',
            index=models.Index(
                fields=['studio', 'sequence'], name='play_events_studio__c2cd1e_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='playevent',
            unique_together={('studio', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(
                fields=['studio', 'state'], name='live_sessio_studio__908bd4_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(
                fields=['started_at'], name='live_sessio_started_64d8ac_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='listenerstatbucket',
            index=models.Index(
                fields=['studio', 'interval', 'bucket_start'],
                name='listener_st_studio__21e747_idx',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='listenerstatbucket',
            unique_together={('studio', 'interval', 'bucket_start')},
        ),
        migrations.AddIndex(
            model_name='listenersession',
            index=models.Index(
                fields=['studio', 'started_at'], name='listener_se_studio__e19068_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='listenersession',
            index=models.Index(
                fields=['studio', 'ended_at'], name='listener_se_studio__8831a6_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='listenersession',
            index=models.Index(
                fields=['studio', 'country'], name='listener_se_studio__40f11a_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='studiomembership',
            index=models.Index(
                fields=['studio', 'role'], name='studio_memb_studio__e47924_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='studiomembership',
            unique_together={('studio', 'user')},
        ),
    ]
