# Generated by Django 5.2.6 on 2025-10-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playevent',
            name='track',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='play_events',
                to='medias.track',
            ),
        ),
    ]
