# Generated by Django 5.2.6 on 2025-10-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
        ('studio', '0002_playevent_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='track',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='playlist_items',
                to='medias.track',
            ),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['track'], name='playlist_it_track_i_7c6f4d_idx'),
        ),
    ]
