# Generated by Django 5.2.7 on 2025-11-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_playlistitem_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenersession',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
