# Generated by Django 5.2.7 on 2026-08-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_listenersession_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='default_bitrate_kbps',
            new_name='default_br_kbps',
        ),
    ]
