# Generated by Django 5.2.7 on 2026-08-24 18:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_rename_default_bitrate_kbps_studio_default_br_kbps'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='default_ch',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='studio',
            name='default_sr_hz',
            field=models.PositiveIntegerField(default=48000),
        ),
        migrations.CreateModel(
            name='StreamingCredential',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=64)),
                ('password_encrypted', models.CharField(max_length=255)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                (
                    'studio',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='streaming_credential',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'streaming_credentials',
            },
        ),
    ]
