# Generated by Django 5.2.7 on 2026-08-22 11:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0005_rename_default_bitrate_kbps_studio_default_br_kbps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'author_type',
                    models.CharField(
                        choices=[('ADMIN', 'Admin'), ('LISTENER', 'Listener')],
                        max_length=8,
                    ),
                ),
                (
                    'listener_client_id',
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ('listener_display_name', models.CharField(blank=True, max_length=80)),
                ('body', models.TextField()),
                (
                    'author',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='chat_messages',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'quoted_message',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quoted_by',
                        to='chat.chatmessage',
                    ),
                ),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chat_messages',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'chat_messages',
                'indexes': [
                    models.Index(
                        fields=['studio', 'created_at'],
                        name='chat_messag_studio__37fc4d_idx',
                    ),
                    models.Index(
                        fields=['studio', 'listener_client_id'],
                        name='chat_messag_studio__0f1aa1_idx',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='ChatMute',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('listener_client_id', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                (
                    'muted_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='chat_mutes_issued',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'studio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chat_mutes',
                        to='studio.studio',
                    ),
                ),
            ],
            options={
                'db_table': 'chat_mutes',
                'indexes': [
                    models.Index(
                        fields=['studio', 'listener_client_id'],
                        name='chat_mutes_studio__892862_idx',
                    )
                ],
            },
        ),
    ]
